### PR TITLE
RFTools Blocks

### PR DESCRIPTION
**Pull request by DeanR97**

### CODE REVIEW

**Review by zISKo666 — CHANGES_REQUESTED** [review]
Hello, I tested your textures in my world and they looking really great 👍 
Only that round shaped machine blocks like the "machinebooster.png" need a bit more love by spending them some sort of round frame. They looking so cut out of the base block.
https://github.com/Soartex-Modded/Modded-1.10.x/pull/28/commits/6e5e4d588dfacd1492a5d14ed0411f3024377a19#diff-47fdb847f590fc28647610fca9e561ae

**Comment by DeanR97** [comment]
I've edited the Block. Hope it's ok :P

**Review by zISKo666 — APPROVED** [review]

**Comment by zISKo666** [comment]
Great work :)

**Comment by zISKo666** [comment]
Can I merge this?
Don't know if I have the permission ;)

**Comment by goldbattle** [comment]
Looks good, thanks again!

**Pull request merged**
