### PR TITLE
MoreFurnaces

### PR DESCRIPTION
**Pull request by mgdgfbhevdyeh**
Most of the texture comes from the previous version
I did not have time but just finished the texture of the Nether furnace
I do texture technology is not very good, I'm slowly learning
Also，my english is no good

### CODE REVIEW

**Comment by Shoeboxam** [comment]
How is the pull request bugged? Do you need any help with fixes?

**Comment by mgdgfbhevdyeh** [comment]
OK,I am Back,I will be fix gui bug.This is one of my little mistakes

**Comment by alfw** [comment]
Hey @mgdgfbhevdyeh , can you rename the folder to More_Furnaces and in the mod.json update text in``mod_dir ``to More_Furnaces,  the ``name`` to More_Furnaces and ``mod_id`` to morefurnaces ? 
This is to follow the format from the other mods.

**Comment by artdude543** [comment]
Yeah as @alfw has mentioned the changes mentioned need to be applied before this gets pulled in. The `mod.json` files are highly important and need to be valid and correct to the repo to ensure our backend scripts run fine without any problems.

**Comment by mgdgfbhevdyeh** [comment]
@alfw Thank you for pointing out that

**Comment by alfw** [comment]
I think you mixed up what i ment with the ``mod.json``. This was the change i ment:

```
{
  "mod_id": "morefurnaces",
  "mod_name": "More Furnaces",
  "mod_dir": "/More_Furnaces/",
  "mod_version": "v1.8.2",
  "mc_version": "1.10.2",
  "mod_authors": ["CubeX2"],
  "url_website": "http://www.minecraftforum.net/topic/506109-",
  "description": "new furnaces"
}
```

You altso need to rename the folder with the textures from ``MoreFurnaces`` to ``More_Furnaces``.
The compile script use the mod_dir part to pull the textures so those need to match up.

If you have more question about it, feel free to ask and ether me or other Soartex Staff will respond!

**Comment by mgdgfbhevdyeh** [comment]
uc 20161203091525
uc 20161203091554
What is this?

**Comment by mgdgfbhevdyeh** [comment]
hmm,
Feeling this Pull request Commits too much
Please turn this  Closed

**Comment by artdude543** [comment]
Closed as on per request.

**Pull request closed without merging**
