### PR TITLE
New textures

### PR DESCRIPTION
**Pull request by Biggbosscurser**
I work on anchors and some of the multiblock textures. Feel free to
comment on my anchor design i am open to work on that.

### CODE REVIEW

**Comment by leagris** [comment]
Why new textures rather than porting from the [1.7.10 version of Railcraft assets](https://github.com/Soartex-Modded/Modded-1.7.x/tree/master/Railcraft/assets/railcraft)?

These blocks already had textures and I think the old ones fit best on the overall style of modded Soartex.

The brick texture you used is mortar-less from StoneBricks whereas the original earlier texture was from Bricks (clay) with mortar.

| Block | Your new texture | 1.7.10 texture |
| --- | --- | --- |
| Admin Anchor |  |  |
| Passive Anchor |  |  |
| Personal Anchor |  |  |
| World Anchor |  |  |
| Blast Furnace |  |  |
| Coal Coke Block |  |  |
| Coke Oven |  |  |
| Water Tank |  |  |

**Comment by Biggbosscurser** [comment]
I have no idea that someone before me works on railcraft textures in soartex. I will definitely going to check the 1.7 assets.

**Comment by Shoeboxam** [comment]
I love keeping alternates around, though. I'd be happy to accept these if they were in an alternates folder. We have a slack chat if you'd like to join. Being able to chat with the other contributors might be helpful in cases like these- it looks like you put a lot of effort into these textures.

**Comment by Biggbosscurser** [comment]
I am unable to get offended by criticism =) i currently am working on an update for this branch to include 1.7 textures with correct names and formats. I love most of the textures but some of them are not my taste so first thing first i feel like i should make a pull request that says "complete fork from 1.7 i dont own them". Then offer some changes to improve them, the decisions of the best will be yours.

I would love to be in a slack chat with contributors.I am very new on texture creation and soartex, chatting while sketching will improve me to the moon and beyond.
Lastly how should i folder the alternative textures?

**Comment by UnPure** [comment]
I dont know if thats still the correct way to do that but atlaeast its the way Soartex has managed the alternative modded texture in the past.
Take a look at for example AE2.
https://github.com/Soartex-Modded/Modded-1.10.x/tree/master/Applied_Energistics_2/assets/appliedenergistics2/textures/guis
There are some alternative textures for the GUI.
I'm pretty sure i have seen them on many mods in the past in the same way.
Just create a "alts" folder in the right place and add your custom textures.
If they are created by your own, i dont see a problem on adding them.
If the community thinks they are better, maybe they get a switch/replaced with the current textures.
Again, i dont know if thats still the right way (thats up to the owners/community) but adding them with a path thats not the current working path shouldnt be a problem anyways because they dont get loaded.

**Comment by Shoeboxam** [comment]
Alright @Biggbosscurser, I just need your email address. I'll send you an invite to join the group.

**Comment by Biggbosscurser** [comment]
@UnPure thanks that was very helpful.

@Shoeboxam I was checking to message you but either i am an idiot or github doesn't have pm features.
my email is biggbosscurser@gmail.com, that was not a surprise or a private info so, there you have it.

**Comment by artdude543** [comment]
The way we currently handle "alts" I'd like to change. Still working out a easy method to have them being separate enough to allow for patch downloading of alts. So it may become it's own repo. (For alts only) and have authors have folders I.E. `Applied_Energistics_2_artdude543` or something like that. Then have a meta file inside which has information about the author and display that on the site. This way it could be shared easily. Which I think would work well.

**Comment by UnPure** [comment]
That sounds good but as long as the system isnt changed we should still add them to a normal alts folder and seperate them later.

**Comment by artdude543** [comment]
For `1.7.x` the system will stay as the current one. But the `1.10.x` will be changed to the new system. Sometime next week. I'm going to make a blog post on what is needed from contributors and how to upgrade / change your alts to the new method. As the current system no one knows if a mod contains alts. As a normal user will not dig through the repo / or the files they just want a download.

**Pull request merged**
